### ISSUE TITLE
Parsing issue for Matlab generated IBIS-AMI

### ISSUE THREAD

**Issue by FranzForstmayr** [capn-freako/PyAMI#10]
I created an IBIS-AMI file in Matlab's Serdes Toolbox just to play around with some modifications but PyBERT fails to parse the .ami file.
The original error message in PyBERT is "list index out of range", triggered by https://github.com/capn-freako/PyAMI/blob/master/pyibisami/ami_parse.py#L73, as the returned dictionary is empty.

It happens with  the following file.

```
(serdes_tx
  (Reserved_Parameters
    (AMI_Version (Usage Info) (Type String) (Value "6.1")
      (Description "This model supports IBIS 6.1. Results may not be valid in earlier versions.")
    )
    (Init_Returns_Impulse (Usage Info) (Type Boolean) (Value True)
      (Description "When True, this model supports AMI_Init (statistical) simulation.")
    )
    (GetWave_Exists (Usage Info) (Type Boolean) (Value True)
      (Description "When True, this model supports AMI_GetWave (time domain) simulation.")
    )
    (Max_Init_Aggressors (Usage Info) (Type Integer) (Value 6)
      (Description "The number of crosstalk aggressors supported by this model.")
    )
    (Modulation (Usage In) (Type String) (Value "NRZ")
      (Description "Specifies whether the model will operate as NRZ or PAM4.")
    )
  )
  (Model_Specific
    (FFE
      (Mode (Usage In) (Type Integer) (List 1 0) (Default 1)
        (List_Tip "fixed" "off")
        (Description "FFE Mode: 0=off, 1=fixed")
      )
      (TapWeights
        (-1 (Usage In) (Type Tap) (Range 0 -2 2) (Default 0)
          (Description "tap -1")
        )
        (0 (Usage In) (Type Tap) (Range 1 -2 2) (Default 1)
          (Description "tap 0")
        )
        (1 (Usage In) (Type Tap) (Range 0 -2 2) (Default 0)
          (Description "tap 1")
        )
        (2 (Usage In) (Type Tap) (Range 0 -2 2) (Default 0)
          (Description "tap 2")
        )
        (3 (Usage In) (Type Tap) (Range 0 -2 2) (Default 0)
          (Description "tap 3")
        )
      )
    )
  )
)
```
The parser error shows:
Expected ) at 18:2 in (Model_Specific

However, all parentheses are matched, why I don't understand what's wrong.

The original ibis-ami model is attached, including the serdes designer definition file (If you have a license).

Unfortunately I've no experience with parsec, or parsing in general, otherwise I could give more sophisticated input.

[serdes.zip](https://github.com/capn-freako/PyAMI/files/6152765/serdes.zip)

**Comment by capn-freako** [comment]
Confirmed reported behavior.
Investigating bug now.

**Comment by capn-freako** [comment]
Posted fix to Anaconda, for download/testing by Franz.

To update:

1. `conda install -c dbanas pyibisami`
2. `conda install -c dbanas pybert`

The new versions of both packages, after updating, should be: 3.3.5.

**Comment by FranzForstmayr** [comment]
Looks  good now.
I tested on Ubuntu, so in copied the files manually from the conda Windows build.

**Comment by capn-freako** [comment]
Thanks, Franz!
I'll get the `PyAMI` update built for Linux and MacOS, tonight.
-db

**Comment by FranzForstmayr** [comment]
Do you still publish via Github, the latest release in here is not the same from conda?
Are there any plans to support a pypi release?

**Comment by capn-freako** [comment]
Franz,

I just pushed the updates to both `PyBERT` and `PyAMI` to GitHub.

I support a pypi release of PyAMI, but not PyBERT.
That's because very few people have had luck getting PyBERT working with a `pip install`.
Almost everyone needs the more advanced package curation offered by `conda`.

**Comment by FranzForstmayr** [comment]
Ok!
I have to admit, that I had trouble installing too, as swig3 is not delivered on ubuntu 20 anymore, took some time until I figured it out. 
Thanks for the fix, I'll close the issue right now!
