### ISSUE TITLE
Tx_Jitter keyword in reserved parameters not recognized

### ISSUE THREAD

**Issue by PetePupalaikis** [capn-freako/PyAMI#16]
I have a parameter that fails in the ami file that looks like this:
```
      		(Tx_Jitter
			(Usage Info)
			(Type Float)
			(DjRj 0.0 0.4e-12 0.35e-12)
         		(Description "Tx jitter")
		) | Rx_Jitter lumped into Tx-jitter 
```
My cursory examination of the ami specification indicates that Tx_Jitter is a valid parameter name, but I don't see it in the reserved parameters list.

**Comment by capn-freako** [comment]
Thanks, Pete!
I'll check this, this weekend, and get it added, if it's missing.
