### ISSUE TITLE
Support for models without GetWave method

### ISSUE THREAD

**Issue by jonnojohnson** [capn-freako/PyAMI#2]
Hi,

If my model doesn't have a GetWave method but does support Init_Returns_Impulse then ami.AMIModel() fails. Could you add support for these cases?

**Comment by capn-freako** [comment]
Thanks for the bug report! I think I've fixed the issue. Please, let me know, if it still doesn't work for you.

Thanks,
-db

**Comment by jonnojohnson** [comment]
Works great.

**Comment by capn-freako** [comment]
Thanks.
