### ISSUE TITLE
Access violation error

### ISSUE THREAD

**Issue by jonnojohnson** [capn-freako/PyAMI#3]
I'm getting the following error when I try to initialize.
I've seen this with a few ami dll's:

myModel.initialize(initData)

``````
---------------------------------------------------------------------------
WindowsError                              Traceback (most recent call last)
<ipython-input-5-2f0882b1047d> in <module>()
----> 1 myModel.initialize(initData)

C:\Users\marnj\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyibisami\amimodel.pyc in initialize(self, init_object)
    287                 byref(self._ami_params_out),
    288                 byref(self._ami_mem_handle),
--> 289                 byref(self._msg)
    290             )
    291         except:

WindowsError: exception: access violation reading 0x0000000000000000```

I'm on win-64, python 2.7 64 bit & pyibis-ami 1.1.6
``````

**Comment by capn-freako** [comment]
Hmm, I can't reproduce your error:

```
In [31]: import pyibisami.amimodel as ami

In [32]: theModel = ami.AMIModel('eASIC_AMI_Tx.dll')

In [33]: initData = ami.AMIModelInitializer({})

In [34]: theModel.initialize(initData)

In [35]:

```

However, I did add some debugging output, at the point in the code where you're stumbling, which might shed some light on just what's going on.

Would you, please, update your PyIBIS-AMI installation to v1.1.7, and re-run your test case, posting the resultant output here?

Thanks!
-db

**Comment by jonnojohnson** [comment]
This is the additional debug output:
```
*****
pyibisami.amimodel.AMIModel.initialize(): Debugging output:
AMIModelInitializer instance:
	ami_params:
		root_name: myDLL
	len(channel_response): 1024
	row_size: 1024
	num_aggressors: 0
	sample_interval: 6.25e-12
	bit_time: 3.87897595035e-11

len(initOut): 1024
ami_params_out: 
_ami_mem_handle: c_char_p('\x80\xca:')
msg: 
--- INFO: Configured 0 items through parameter string. 
--- INFO: Init. setup 1: P.Filter #1 =  0, P.Filter #2 =  0, VGA =  0 

pyibisami.amimodel.AMIModel.initialize(): End debugging output.
*****
```

**Comment by capn-freako** [comment]
So, you have a non-integral number of samples per bit (6.2).
This is, usually, an error.
Can you try your experiment, using an integral number of samples per bit?
(An integral power of 2 is, usually, best.)

**Comment by jonnojohnson** [comment]
I'm getting the same error if I set the samples per bit to exactly 8.
I think I can share a dll with you that exhibits this behavior later.

**Comment by capn-freako** [comment]
Okay. If you can send me one that was built with debugging symbols enabled, that will help.

**Comment by jonnojohnson** [comment]
I've tested a few more models that I could get my hands on and so far I only get this with one dll. Unfortunately it's a dll I need to use but I don't have permission to share it.

**Comment by capn-freako** [comment]
Have you tried using it in some other tool, to see if you get the same
access violation error?

**Comment by jonnojohnson** [comment]
Yes it works fine in ADS.

**Comment by capn-freako** [comment]
If you can get a “debug” build from the vendor, I can try to guide you through a gdb debug session.
In this case, a “debug” version just means that the DLL/SO was compiled with symbols enabled.
This will let us identify at what point in the C/C++ code the crash (i.e. - access violation) is occurring.

Regards,
-db

**Comment by capn-freako** [comment]
Closing, due to no response in over 3 years.
