### ISSUE TITLE
Py3K support missing

### ISSUE THREAD

**Issue by martinATtug** [capn-freako/PyAMI#4]
It looks like there is no support for Python 3 and moreover this fact seems to be undocumented.
```
C:\Users\xxxxxxxxxxx\Programme\WinPython-64bit-3.4.4.2\scripts>pip3 install PyAMI
Collecting PyAMI
  Using cached pyAMI-4.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXXXXX~1\AppData\Local\Temp\pip-build-x_1uco3u\PyAMI\setup.
py", line 87
        print __doc__
                    ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\XXXXXX~1\AppData\Local\Temp\pip-build-x_1uco3u\PyAMI\
```

**Comment by capn-freako** [comment]
Yes, I'm afraid I'm still using Python v2.7.
-db

**Comment by martinATtug** [comment]
Am 28.03.2017 um 18:24 schrieb David Banas:
> Yes, I'm afraid I'm still using Python v2.7.
> -db

Neither works with my Python 2.7 distro. Pulls in the obsolete
"distribute" package via a dependency and then fails on a clamped
version of "certifi" :-(

      File "c:\users\xxxxxx~1\appdata\local\temp\tmp3g29js\distribute-0.6.28\pkg_resources.py", line 592, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (certifi 14.5.14 (c:\users\xxxxxxxxxx\programme\winpython-64bit-2.7.9.3\python-2.7.9.amd64\lib\site-packages), Requirement.parse('certifi==1.0.1'))
    

Don't bother to investigate! I am giving up on PyAMI.

**Comment by jdpatt** [comment]
I've done some work to make it compatible with both 2/3 so that PyBERT can be used with python 3.  You should run tox from the base conda environment.  Running from another environment causes issues when generating virtualenvs.

I still need to get the examples working to insure that nothing else was broken.

**Comment by capn-freako** [comment]
Closing after having merged in David Patterson's changes, for Python 3 compatibility.
